
INSERT INTO products (codigo, categoria, nombre, descripcion, precio, url) VALUES
('TC001', 'Tortas Cuadradas', 'Torta Cuadrada de Chocolate', 'Deliciosa torta de chocolate con capas de ganache y un toque de avellanas. Personalizable con mensajes especiales', 45000, 'https://brigams.pe/wp-content/uploads/chocolate-2.jpg'),
('TC002', 'Tortas Cuadradas', 'Torta Cuadrada de Frutas', 'Una mezcla de frutas frescas y crema chantilly sobre un suave bizcocho de vainilla, ideal para celebraciones.', 50000, 'https://brigams.pe/wp-content/uploads/tutifruti-2-1000x667.jpg'),
('TT001', 'Tortas Circulares', 'Torta Circular de Vainilla', 'Bizcocho de vainilla clásico relleno con crema pastelera y cubierto con un glaseado dulce, perfecto para cualquier ocasión.', 40000, 'https://i1.wp.com/isabelvermal.com/wp-content/uploads/2023/03/IV-305-1.jpg?ssl=1'),
('TT002', 'Tortas Circulares', 'Torta Circular de Manjar', 'Torta tradicional chilena con manjar y nueces, un deleite para los amantes de los sabores dulces y clásicos.', 42000, 'https://www.elingenio.cl/productos/bizcocho-manjar-lucuma.jpg'),
('PI001', 'Postres Individuales', 'Mousse de Chocolate', 'Postre individual cremoso y suave, hecho con chocolate de alta calidad, ideal para los amantes del chocolate.', 5000, 'https://imag.bonviveur.com/mousse-de-chocolate-negro-casera.jpg'),
('PI002', 'Postres Individuales', 'Tiramisú Clásico', 'Un postre italiano individual con capas de café, mascarpone y cacao, perfecto para finalizar cualquier comida.', 5500, 'https://www.gourmet.cl/wp-content/uploads/2016/09/Tiramisu.png'),
('PSA001', 'Productos Sin Azúcar', 'Torta Sin Azúcar de Naranja', 'Torta ligera y deliciosa, endulzada naturalmente, ideal para quienes buscan opciones más saludables.', 48000, 'https://cocinachilena.cl/wp-content/uploads/2010/08/torta-naranja-10-scaled.jpg'),
('PSA002', 'Productos Sin Azúcar', 'Cheesecake Sin Azúcar', 'Suave y cremoso, este cheesecake es una opción perfecta para disfrutar sin culpa.', 47000, 'https://www.jamieoliverenespañol.com/wp-content/uploads/2015/05/cheesecake.jpg'),
('PT001', 'Pastelería Tradicional', 'Empanada de Manzana', 'Pastelería tradicional rellena de manzanas especiadas, perfecta para un dulce desayuno o merienda.', 3000, 'https://lacocinadefrabisa.lavozdegalicia.es/wp-content/uploads/2017/02/empanada-manzana-5-640x640.jpg'),
('PT002', 'Pastelería Tradicional', 'Tarta de Santiago', 'Tradicional tarta española hecha con almendras, azúcar, y huevos, una delicia para los amantes de los postres clásicos.', 6000, 'https://recetasdecocina.elmundo.es/wp-content/uploads/2025/03/tarta-de-santiago.jpg'),
('PG001', 'Productos Sin Gluten', 'Brownie Sin Gluten', 'Rico y denso, este brownie es perfecto para quienes necesitan evitar el gluten sin sacrificar el sabor.', 4000, 'https://mividaenundulce.com/wp-content/uploads/2014/01/dsc_1744.jpg'),
('PG002', 'Productos Sin Gluten', 'Pan Sin Gluten', 'Suave y esponjoso, ideal para sándwiches o para acompañar cualquier comida.', 3500, 'https://glutendence.com/wp-content/uploads/2022/09/Pan-sarraceno-y-quinoa-1024x576.jpg'),
('PV001', 'Productos Vegana', 'Torta Vegana de Chocolate', 'Torta de chocolate húmeda y deliciosa, hecha sin productos de origen animal, perfecta para veganos.', 50000, 'https://www.limaorganica.pe/wp-content/uploads/2020/01/arilu-vegan-choco-cake-700x460.jpg'),
('PV002', 'Productos Vegana', 'Galletas Veganas de Avena', 'Crujientes y sabrosas, estas galletas son una excelente opción para un snack saludable y vegano.', 4500, 'https://i.blogs.es/8792e6/galletas-avea-tahina-datiles/840_560.jpg'),
('TE001', 'Tortas Especiales', 'Torta Especial de Cumpleaños', 'Diseñada especialmente para celebraciones, personalizable con decoraciones y mensajes únicos.', 55000, 'https://fridolin.com.bo/wp-content/uploads/2020/08/Placa-p-tortas-producto.jpg'),
('TE002', 'Tortas Especiales', 'Torta Especial de Boda', 'Elegante y deliciosa, esta torta está diseñada para ser el centro de atención en cualquier boda.', 60000, 'https://static.wixstatic.com/media/a18991_1867d6ee4e2f45e1b90010c8b9044c19~mv2.jpg/v1/fill/w_520,h_414,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/a18991_1867d6ee4e2f45e1b90010c8b9044c19~mv2.jpg');
